site_name: Querido Diário - Documentação

copyright: "Copyright &copy; 2024 Wildemberg Sales"

theme:
  name: material
  language: "pt"
  palette:
    primary: #5e408f 
    accent: #ff8500
  features:
    - navigation.tabs

  text: "Open Sans"
  code: "sans-serif"
  logo: assets/images/logo.png
  #favicon: assets/images/logo2.png

nav:
  - Início: index.md
  - Atas de Reunião:
    - Reunião 01: atas-reuniao/ata-04-03-2024.md
  - Planejamento:
    - Metodologia: index.md
    - Ferramentas: index.md
    - Cronograma: index.md
    - HeatMap: index.md
  - Elicitação de Requisitos:
    - Perfil de usuário: index.md
    - Brainstorm: index.md
    - Pesquisa de Campo (formulário): index.md
  - Priorização:
    - In or Out: index.md
  - Modelagem de requisitos:
    - Casos de Uso: index.md
    - User Story: index.md
    - Backlog: index.md
  - Prototipagem:
    - Baixa Fidelidade: index.md
    - Alta Fidelidade: index.md
  - Arquitetura do Software:
    - Diagrama de classe: index.md
    - Diagrama de pacotes: index.md
    - Representação Arquitetural: index.md
  - Banco de dados: index.md